apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "ords.fullname" . }}
  labels:
    {{- include "ords.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ords.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "ords.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: container-registry.oracle.com/database/ords:latest
          ports:
            - containerPort: 8181
              name: ords
          volumeMounts:
            - name: storageords
              mountPath: /etc/ords/config
          volumeMounts:
            - name: secretords
              mountPath: /opt/oracle/variables
          imagePullPolicy: IfNotPresent
      volumes:
        - name: storageords
          persistentVolumeClaim:
            claimName: ords-pvc
        - name: secretords
          secret:
            name: {{ .Values.ords.secret.secretName }}






