apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ords.fullname" . }}-ords-config
data:
  ords_setup.sh: |-
    #!/bin/bash
    ords install --admin-user $ADMIN_USER --proxy-user --db-hostname $DB_HOST --db-port $DB_PORT --db-servicename $DB_SERVICENAME --feature-sdw true --password-stdin <<EOF
    $ADMIN_PWD
    $PROXY_PWD
    EOF
    cd /etc/ords/config
    curl -o apex.zip https://download.oracle.com/otn_software/apex/apex-latest.zip
    jar xvf apex.zip
    rm apex.zip
    chmod -R 755 apex
    ords config set standalone.static.path /etc/ords/config/apex/images
{{- if eq .Values.service.useSSL true }}
    ords config set standalone.https.port 8443
    ords config set standalone.https.host {{ .Values.service.virtualHostName }}
    ords config set standalone.https.cert /ssl/tls.crt
    ords config set standalone.https.cert.key /ssl/tls.key
{{- end }}

