apiVersion: v1
kind: Secret
metadata:
  name: {{ include "var.fullname" . }}-secret
stringData:
   DB_SID: oml4pydb
   DB_PDB: oml4py 
   DB_MEMORY: 3GB
   DB_PASSWORD: {{ .Values.database.initialpwd }}



