kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "var.fullname" . }}-scripts-config
data:
    testconn.sh: "/opt/oracle/sqlcl/bin/sql /nolog << EOF\n
      whenever sqlerror exit failure;\n
      connect sys/$DB_PASSWORD@{{ .Values.database.hostname }}:1521/orclpdb1 as sysdba\n
      select * from dual;\n
      exit;\nEOF\n
      if [ $? -eq 0 ] ; then echo \"connect successful\" ; else echo \"DB connect failed, waiting 2 mins and exiting...\" ; sleep 120 ; exit 5 ; fi "
    01_setPassword.sh: "#!/bin/bash\nsqlplus / AS SYSDBA << EOF\n
      ALTER USER SYS IDENTIFIED BY \"$DB_PASSWORD\";\n
      ALTER USER SYSTEM IDENTIFIED BY \"$DB_PASSWORD\";\n
      ALTER SESSION SET CONTAINER=ORCLPDB1;\n
      ALTER USER PDBADMIN IDENTIFIED BY \"$DB_PASSWORD\";\n
      exit;\nEOF\n"
    02_setupOML.sh: "#!/bin/bash\nsqlplus sys/$DB_PASSWORD@127.0.0.1/ORCLPDB1:1521 as sysdba << EOF \n
     ALTER PROFILE DEFAULT LIMIT PASSWORD_VERIFY_FUNCTION NULL; \n
     @/opt/oracle/product/21c/dbhome_1/oml4py/server/pyqcfg.sql \n
     exit;\nEOF\n"
    InitAll.sh: "/bin/bash /scripts/InitSchema-01.sh\n /bin/bash /scripts/InitSchema-02.sh\n /bin/bash /scripts/InitSchema-03.sh\n /bin/bash /scripts/InitSchema-04.sh\n"
    InitSchema-01.sh: "/opt/oracle/sqlcl/bin/sql sys/\"$DB_PASSWORD\"@{{ .Values.database.hostname }}/ORCLPDB1:1521
      as sysdba << EOF\necho Initialisieren des Schemas\necho ==========================\n\necho
      1) Create Users\necho ---------------\n@/scripts/dbhelper-01a-create_user_oml4pyuser.sql\n@/scripts/dbhelper-01b-create_user_ds1.sql\n@/scripts/dbhelper-01c-create_user_ds2.sql\necho
      Create Table\n\necho 2) Create Tables (a)\necho --------------------\n@/scripts/dbhelper-02-create_table_raddauerzaehlstellen.sql\n\necho
      3) Create Sequences\necho -------------------\n@/scripts/dbhelper-03-create_sequence_raddauerzaehlstellen.sql\n\necho
      4) Create Trigger\necho -----------------\n@/scripts/dbhelper-04-create_trigger_raddauerzaehlstellen.sql\nEOF\n"
    InitSchema-02.sh: "curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_01_15min.csv -o /tmp/rad_2022_01_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_02_15min.csv -o /tmp/rad_2022_02_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_03_15min.csv -o /tmp/rad_2022_03_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_04_15min.csv -o /tmp/rad_2022_04_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_05_15min.csv -o /tmp/rad_2022_05_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_06_15min.csv -o /tmp/rad_2022_06_15min.csv \n
      curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/rad_2022_07_15min.csv -o /tmp/rad_2022_07_15min.csv \n
      cd /tmp \n
      /usr/lib/oracle/21/client64/bin/sqlldr oml4pyuser/oml4pypwd@//{{ .Values.database.hostname }}/ORCLPDB1:1521
      control=/scripts/dbhelper-05-load-raddauerzaehlstellen.ctl\n"
    InitSchema-03.sh: "curl https://raw.githubusercontent.com/ilfur/VirtualAnalyticRooms/main/VARdata/masked_data.DMP -o masked_data.DMP \n/usr/lib/oracle/21/client64/bin/impdp oml4pyuser/oml4pypwd@//{{ .Values.database.hostname }}/ORCLPDB1:1521
      DIRECTORY=DPDIR DUMPFILE=masked_data.DMP TABLES=oml4pyuser.raddauerzaehlstellen
      REMAP_TABLE=oml4pyuser.raddauerzaehlstellen:raddauerzaehlstellen_m\n"
    InitSchema-04.sh: "/opt/oracle/sqlcl/bin/sql sys/\"$DB_PASSWORD\"@{{ .Values.database.hostname }}/ORCLPDB1:1521
      as sysdba << EOF\necho 6) Create Views\necho ---------------\n@/scripts/dbhelper-06a-create_view_v_raddauerzaehlstellen_d.sql\n@/scripts/dbhelper-06b-create_view_v_raddauerzaehlstellen_v.sql\n\necho
      7) Grant DB Object Privileges\necho -----------------------------\n@/scripts/dbhelper-07a-grant_to_user_ds1.sql\n@/scripts/dbhelper-07b-grant_to_user_ds2.sql\n\necho
      8) Create Synonyms\necho ------------------\n@/scripts/dbhelper-08a-create_synonym_raddauerzaehlstellen_d.sql\n@/scripts/dbhelper-08b-create_synonym_raddauerzaehlstellen_v.sql\n@/scripts/dbhelper-08c-create_synonym_raddauerzaehlstellen_m.sql\necho
      Schema intialisiert\nexit;\nEOF\n"
    dbhelper-01a-create_user_oml4pyuser.sql: "ALTER SESSION SET CONTAINER=orclpdb1;\nDROP
      USER oml4pyuser CASCADE;\nCREATE USER oml4pyuser IDENTIFIED BY oml4pypwd ;\nALTER
      USER oml4pyuser DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;\nDROP TABLESPACE
      TBS_DMS INCLUDING CONTENTS AND DATAFILES;\nCREATE TABLESPACE TBS_DMS DATAFILE
      'TBS_DMS.dat' SIZE 10M AUTOEXTEND ON;\nALTER USER oml4pyuser QUOTA UNLIMITED
      ON TBS_DMS;\nDROP DIRECTORY DPDIR;\nCREATE OR REPLACE DIRECTORY DPDIR as
      '/dpdir';\nGRANT read, write ON DIRECTORY DPDIR to oml4pyuser;\nGRANT UNLIMITED
      TABLESPACE TO oml4pyuser;\nGRANT CREATE SESSION TO oml4pyuser;\nGRANT CREATE
      TABLE TO oml4pyuser;\nGRANT CREATE VIEW TO oml4pyuser;\nGRANT CREATE TRIGGER
      TO oml4pyuser;\nGRANT CREATE SEQUENCE TO oml4pyuser;\nGRANT CREATE PROCEDURE
      TO oml4pyuser;\nGRANT CREATE MINING MODEL TO oml4pyuser;\nGRANT EXECUTE
      ON CTXSYS.CTX_DDL TO oml4pyuser;\nGRANT PYQADMIN TO oml4pyuser;\nGRANT RESTRICTED
      SESSION TO oml4pyuser;"
    dbhelper-01b-create_user_ds1.sql: "ALTER SESSION SET CONTAINER=orclpdb1;\nDROP
      USER ds1 CASCADE;\nCREATE USER ds1 IDENTIFIED BY ds1pwd;\nALTER USER ds1
      DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;\nGRANT CREATE SESSION TO
      ds1;\nGRANT CREATE TABLE TO ds1;\nGRANT CREATE VIEW TO ds1;\nGRANT CREATE
      PROCEDURE TO ds1;\nGRANT CREATE MINING MODEL TO ds1;\nGRANT EXECUTE ON CTXSYS.CTX_DDL
      TO ds1;\nGRANT PYQADMIN TO ds1;\nGRANT RESTRICTED SESSION TO ds1;\n"
    dbhelper-01c-create_user_ds2.sql: "ALTER SESSION SET CONTAINER=orclpdb1;\nDROP
      USER ds2 CASCADE;\nCREATE USER ds2 IDENTIFIED BY ds2pwd;\nALTER USER ds2
      DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;\nGRANT CREATE SESSION TO
      ds2;\nGRANT CREATE TABLE TO ds2;\nGRANT CREATE VIEW TO ds2;\nGRANT CREATE
      PROCEDURE TO ds2;\nGRANT CREATE MINING MODEL TO ds2;\nGRANT EXECUTE ON CTXSYS.CTX_DDL
      TO ds2;\nGRANT PYQADMIN TO ds2;\nGRANT RESTRICTED SESSION TO ds2;\n"
    dbhelper-02-create_table_raddauerzaehlstellen.sql: "xxx\nCREATE TABLE oml4pyuser.raddauerzaehlstellen\n
      \                      ( \"RDZID\"         INTEGER\n                       ,
      \"DATUM\"         VARCHAR(10)\n                       , \"UHRZEIT_START\"
      VARCHAR(5)\n                       , \"UHRZEIT_STOP\"  VARCHAR(5)\n                       ,
      \"ZAEHLSTELLE\"   VARCHAR(100)\n                       , \"RICHTUNG_1\"    INTEGER\n
      \                      , \"RICHTUNG_2\"    INTEGER\n                       ,
      \"GESAMT\"        INTEGER\n                       ) \n       TABLESPACE
      \"TBS_DMS\"\n;\n"
    dbhelper-03-create_sequence_raddauerzaehlstellen.sql: CREATE SEQUENCE oml4pyuser.sq_raddauerzaehlstellen
      INCREMENT BY 1 START WITH 1;
    dbhelper-04-create_trigger_raddauerzaehlstellen.sql: "CREATE OR REPLACE TRIGGER
      oml4pyuser.tr_raddauerzaehlstellen\nBEFORE INSERT ON oml4pyuser.RADDAUERZAEHLSTELLEN\nFOR
      EACH ROW\nBEGIN\n\tIF :new.RDZID IS NULL THEN\n\t\tSELECT oml4pyuser.SQ_RADDAUERZAEHLSTELLEN.nextval
      INTO :new.rdzid FROM DUAL;\n\tEND IF;\nEND; "
    dbhelper-05-load-raddauerzaehlstellen.ctl: "OPTIONS\n( \n  SKIP=1\n, ROWS=10000\n,
      BINDSIZE=2000000000\n, READSIZE=2000000000\n)\nload data\ninfile '/tmp/rad_2022_*_15min.csv'\ninto
      table oml4pyuser.raddauerzaehlstellen\nfields terminated by \",\"\n( DATUM\n,
      UHRZEIT_START\n, UHRZEIT_STOP\n, ZAEHLSTELLE\n, RICHTUNG_1\n, RICHTUNG_2\n,
      GESAMT\n)\n"
    dbhelper-06a-create_view_v_raddauerzaehlstellen_d.sql: "CREATE OR REPLACE FORCE
      EDITIONABLE VIEW oml4pyuser.v_raddauerzaehlstellen_d\nAS \nSELECT rdzid\n
      \    , CASE \n       WHEN SubStr( datum, 3, 1 ) != '.'\n       THEN To_Date(
      datum, 'YYYY.MM.DD' )\n       ELSE To_Date( datum, 'DD.MM.YYYY' ) \n       END
      AS datum\n     , CASE \n       WHEN SubStr( datum, 3, 1 ) != '.'\n       THEN
      To_Timestamp( Concat( Concat( datum\n                                        ,
      ' '\n                                        )\n                                ,
      uhrzeit_start\n                                )\n                        ,
      'YYYY.MM.DD HH24:MI'\n                        )\n       ELSE  To_Timestamp(
      Concat( Concat( datum\n                                         , ' '\n
      \                                        )\n                                 ,
      uhrzeit_start\n                                 )\n                         ,
      'DD.MM.YYYY HH24:MI'\n                         ) \n       END AS ts\n
      \    , zaehlstelle\n     , richtung_1\n     , richtung_2\n     , gesamt\n
      \ FROM oml4pyuser.raddauerzaehlstellen\n ORDER BY datum\n; \n"
    dbhelper-06b-create_view_v_raddauerzaehlstellen_v.sql: "CREATE OR REPLACE FORCE
      EDITIONABLE VIEW oml4pyuser.v_raddauerzaehlstellen_v\nAS \nSELECT Min(rdzid)
      AS rdzid\n     , CASE \n       WHEN SubStr( datum, 3, 1 ) != '.'\n       THEN
      To_Date( datum, 'YYYY.MM.DD' )\n       ELSE To_Date( datum, 'DD.MM.YYYY' )
      \n       END AS datum\n     , zaehlstelle\n     , Sum(richtung_1) AS richtung_1\n
      \    , Sum(richtung_2) AS richtung_2\n     , Sum(gesamt) AS gesamt\n  FROM
      oml4pyuser.raddauerzaehlstellen\n GROUP BY datum\n        , zaehlstelle\n
      ORDER BY datum\n;\n"
    dbhelper-07a-grant_to_user_ds1.sql: "GRANT READ ON oml4pyuser.v_raddauerzaehlstellen_d
      TO ds1;\nGRANT READ ON oml4pyuser.v_raddauerzaehlstellen_v TO ds1;"
    dbhelper-07b-grant_to_user_ds2.sql: GRANT READ ON oml4pyuser.v_raddauerzaehlstellen_v
      TO ds2;
    dbhelper-08a-create_synonym_raddauerzaehlstellen_d.sql: |
      xxx
      CREATE OR REPLACE EDITIONABLE SYNONYM oml4pyuser.s_raddauerzaehlstellen_d
      FOR oml4pyuser.v_raddauerzaehlstellen_d
      ;
      CREATE OR REPLACE EDITIONABLE SYNONYM ds1.s_raddauerzaehlstellen_d
      FOR oml4pyuser.v_raddauerzaehlstellen_d
      ;
    dbhelper-08b-create_synonym_raddauerzaehlstellen_v.sql: |
      CREATE OR REPLACE EDITIONABLE SYNONYM oml4pyuser.s_raddauerzaehlstellen_v
      FOR oml4pyuser.v_raddauerzaehlstellen_v
      ;
      CREATE OR REPLACE EDITIONABLE SYNONYM ds1.s_raddauerzaehlstellen_v
      FOR oml4pyuser.v_raddauerzaehlstellen_v
      ;
      CREATE OR REPLACE EDITIONABLE SYNONYM ds2.s_raddauerzaehlstellen_v
      FOR oml4pyuser.v_raddauerzaehlstellen_v
      ;
    dbhelper-08c-create_synonym_raddauerzaehlstellen_m.sql: |-
      CREATE OR REPLACE EDITIONABLE SYNONYM ds2.s_raddauerzaehlstellen_m
      FOR oml4pyuser.raddauerzaehlstellen_m
      ;
    oml4pysrvinit.sql: "#./sql sys/\"$DB_PASSWORD\"@localhost:1521:orclcdb as sysdba\n#spool
      install.txt\n#ALTER Session Set container=orclpdb1;\n#ALTER PROFILE DEFAULT
      LIMIT PASSWORD_VERIFY_FUNCTION NULL;\n#@$ORACLE_HOME/oml4py/server/pyqcfg.sql\n#define
      permtbl_value = SYSAUX\n#define temptbl_value = TEMP\n#define orahome_value
      = /opt/oracle/product/21c/dbhome_1\n#define pythonhome = /opt/oracle/product/21c/dbhome_1/python\nALTER
      SESSION SET Container=orclpdb1;\nCREATE USER oml4pyuser Identified By \"$DB_PASSWORD\";\nALTER
      USER oml4pyuser DEFAULT TABLESPACE USERS quota unlimited ON USERS;\nGRANT
      CREATE SESSION TO oml4pyuser;\nGRANT CREATE TABLE TO oml4pyuser;\nGRANT
      CREATE VIEW TO oml4pyuser;\nGRANT CREATE PROCEDURE TO oml4pyuser;\nGRANT
      CREATE MINING MODEL TO oml4pyuser;\nGRANT EXECUTE ON CTXSYS.CTX_DDL TO oml4pyuser;\nGRANT
      PYQADMIN TO oml4pyuser;\nquit"
