apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "ggate.fullname" . }}
  labels:
    {{- include "ggate.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
            {{- include "ggate.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "ggate.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image.imageName }}
          ports:
            - containerPort: 443
              name: ggate
          volumeMounts:
            - name: u01
              mountPath: /u01/ogg/scripts
            - name: u02
              mountPath: /u02
            - name: u03
              mountPath: /u03
          imagePullPolicy: IfNotPresent
          env:
            - name: OGG_DEPLOYMENT
              value: {{ .Values.ogg.deploymentName }}
            - name: OGG_ADMIN
              valueFrom:
                 secretKeyRef:
                    name: {{ .Values.ogg.adminSecret }}
                    key: {{ .Values.ogg.usernameKey }}
            - name: OGG_ADMIN_PWD
              valueFrom:
                 secretKeyRef:
                    name: {{ .Values.ogg.adminSecret }}
                    key: {{ .Values.ogg.passwordKey }}
      volumes:
        - name: u01
          persistentVolumeClaim:
            claimName: {{ include "ggate.fullname" . }}-u01-pvc
        - name: u02
          persistentVolumeClaim:
            claimName: {{ include "ggate.fullname" . }}-u02-pvc
        - name: u03
          persistentVolumeClaim:
            claimName: {{ include "ggate.fullname" . }}-u03-pvc





