apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "var.fullname" . }}-db-prepare-config
data:
  prepare.sh: |-
    #!/bin/bash 
    cd ~
    git clone https://github.com/ilfur/gg_microhacks_scripts
    cd gg_microhacks_scripts

    export PATH=/opt/oracle/instantclient_23_4:$PATH
    export LD_LIBRARY_PATH=/opt/oracle/instantclient_23_4:$LD_LIBRARY_PATH

    . ./init_targetdb_adb.sh
    . ./init_srcdb_23ai.sh
    . ./config_goldengate.sh

  testconn.sh: |-
    #!/bin/bash 
    export PATH=/opt/oracle/instantclient_23_4:$PATH
    export LD_LIBRARY_PATH=/opt/oracle/instantclient_23_4:$LD_LIBRARY_PATH
     sqlplus system/$ADMIN_PWD@//$SRC_URL << EOF 
     whenever sqlerror exit failure; 
     select * from dual; 
     create table mydummy (mycol number);
     drop table mydummy;
     exit; 
     EOF
     if [ $? -eq 0 ] ; then echo "connect successful" ; sleep 10 ; else echo "DB connect failed, waiting 1 min and exiting..." ; sleep 60 ; exit 5 ; fi 
