apiVersion: v1
kind: Service
metadata:
  name: {{ include "var.fullname" . }}-db23ai
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: db
  ports:
    - port: 1521
      targetPort: 1521
      appProtocol: tcp
      name: listener
  type: ClusterIP

