apiVersion: v1
kind: Service
metadata:
  name: {{ include "var.fullname" . }}-jupyter-service
spec:
  ports:
  - name: jupyter
    port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/name: {{ include "var.fullname" . }}-jupyter
  type: ClusterIP
{{- if ne .Values.services.external.type "none" }}
{{- if eq .Values.services.external.type "ingress" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "var.fullname" . }}-ingress
spec:
  ingressClassName: {{ .Values.services.external.ingressClass }}
{{- if eq .Values.services.external.ingressClass "nginx" }}
  tls:
  - hosts:
    - {{ .Values.services.external.vhostName }}
    secretName: {{ .Values.services.external.tlsSecretName }}
{{- end }}
  rules:
  - host: {{ .Values.services.external.vhostName }}
    http:
      paths:
      - path: /jupyter
        pathType: Prefix
        backend:
          service:
            name:  {{ include "var.fullname" . }}-jupyter-service
            port:
              number: 8080
{{- end }}
{{- end }}

