apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "var.fullname" . }}-daa-u02-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.logSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "var.fullname" . }}-daa-u03-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.trailSize }}

