apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "ggate.fullname" . }}
  labels:
    {{- include "ggate.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
            {{- include "ggate.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "ggate.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      #securityContext:
        #fsGroup: 1000
        #runAsUser: 994
      initContainers:
      - command:
        - /bin/bash
        - -c
        - chown 54321 /u02; chown 54321 /u03
        image: container-registry.oracle.com/goldengate/goldengate-oracle:23.10.3.25.11
        imagePullPolicy: IfNotPresent
        name: setperms
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /u02
          name: u02
        - mountPath: /u03
          name: u03
      containers:
{{- if eq .Values.statsdExporter.enabled true }}
        - name: statsd-exporter
          image: {{ .Values.image.statsdExporterImage }} 
          imagePullPolicy: Always
          args: ["--statsd.mapping-config", "/config/statsd-mapping.yaml", "--log.level", "debug"]
          ports:
          - containerPort: 9102
            name: http
            protocol: TCP
          - containerPort: 9125
            name: push
            protocol: UDP
          volumeMounts:
          - mountPath: /config
            name: statsd-config
{{- end }}
        - name: app
          image: {{ .Values.image.imageName }}
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  capabilities:
          #    drop:
          #    - ALL
          #  runAsNonRoot: true
          #  seccompProfile:
          #    type: RuntimeDefault
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: 443
              name: https-ggate
            - containerPort: 80
              name: http-ggate
          volumeMounts:
            - name: u02
              mountPath: /u02
            - name: u03
              mountPath: /u03
          imagePullPolicy: IfNotPresent
          env:
            - name: OGG_DEPLOYMENT
              value: {{ .Values.ogg.deploymentName }}
            - name: OGG_ADMIN
              valueFrom:
                 secretKeyRef:
                    name: {{ .Values.ogg.adminSecret }}
                    key: {{ .Values.ogg.usernameKey }}
            - name: OGG_ADMIN_PWD
              valueFrom:
                 secretKeyRef:
                    name: {{ .Values.ogg.adminSecret }}
                    key: {{ .Values.ogg.passwordKey }}
      volumes:
{{- if eq .Values.statsdExporter.enabled true }}
        - name: statsd-config
          configMap:
            defaultMode: 420
            name: {{ include "ggate.fullname" . }}-statsd-mapping-config
{{- end }}
        - name: u02
          persistentVolumeClaim:
            claimName: {{ include "ggate.fullname" . }}-u02-pvc
        - name: u03
          persistentVolumeClaim:
            claimName: {{ include "ggate.fullname" . }}-u03-pvc





