apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "var.fullname" . }}-db      
  labels:
    {{- include "var.labels" . | nindent 4 }}
    component: db
spec:
  selector:
    matchLabels:
      {{- include "var.selectorLabels" . | nindent 6 }}      
      component: db
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "var.selectorLabels" . | nindent 8 }}
        component: db
    spec:
      containers:
        - name: db
          image: container-registry.oracle.com/database/adb-free:latest-23ai
          ports:
            - containerPort: 1521
              name: tls
            - containerPort: 1522
              name: mtls
            - containerPort: 8443
              name: ords
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: oradata
              mountPath: /u01/data
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKLOAD_TYPE
              value: "ATP"
            - name: DATABASE_NAME
              value: {{ .Values.database.dbname }}
            - name: WALLET_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_PASSWORD
            - name: ADMIN_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: {{ include "var.fullname" . }}-secret
                  key: DB_PASSWORD
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: {{ include "var.fullname" . }}-oradata-pvc
