apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "var.fullname" . }}-oradata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
