apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.dbname }}
spec:
  selector:
      {{- include "var.selectorLabels" . | nindent 6 }}
      component: db
  ports:
    - port: 1521
      targetPort: 1522
      appProtocol: tcp
      name: tls
    - port: 1522
      targetPort: 1521
      appProtocol: tcp
      name: mtls
    - port: 8443
      targetPort: 8443
      appProtocol: tcp
      name: ords
    - port: 27017
      targetPort: 27017
      appProtocol: tcp
      name: mongo
  type: ClusterIP

