apiVersion: v1
kind: Secret
metadata:
  name: {{ include "var.fullname" . }}-secret
stringData:
   DB_PDB: {{ .Values.database.dbname }}
   DB_PASSWORD: {{ .Values.database.initialpwd }}



