apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ggate.fullname" . }}-u01-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.configSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ggate.fullname" . }}-u02-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.logSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ggate.fullname" . }}-u03-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.trailSize }}

